version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.1
  aws-cli: circleci/aws-cli@1.2.1


jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.1
      - image: circleci/postgres:9.5-alpine
      - image: 'cimg/node:13.12-browser'
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: books_app_test
          POSTGRES_PASSWORD: ""
      - image: redis
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - ruby/rspec-test
  build:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get update
      - run: echo $CIRCLE_BRANCH
      - run:
          name: Remove untracked files
          command: git clean -f
workflows:
  version: 2
  build_environment:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - testing